<a href="https://colab.research.google.com/github/chiragkhachane/DBMS_data_generator/blob/main/UB_DBMS_Data_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import string

# Function to generate random alphanumeric strings
def random_string(length):
    letters = string.ascii_letters + string.digits
    return ''.join(random.choice(letters) for i in range(length))

# Function to generate random date in 'YYYY-MM-DD' format
def random_date():
    year = random.randint(1995, 2023)
    month = random.randint(1, 12)
    day = random.randint(1, 28)
    return f"{year}-{month:02d}-{day:02d}"

# Function to generate random time in 'HH:MM:SS' format
def random_time():
    hour = random.randint(8, 18)
    minute = random.randint(0, 59)
    return f"{hour:02d}:{minute:02d}:00"

# Function to generate and export data to SQL file
def generate_data(num_records):
    with open("class_schedule_data.sql", "w") as sql_file:
        # Generate Departments data
        for dept_id in range(1, 6):
            dept_name = f"Department-{dept_id}"
            dept_head = f"Head-{dept_id}"
            location = f"Location-{dept_id}"
            sql_file.write(f"INSERT INTO Departments (DepartmentID, DepartmentName, DepartmentHead, Location) "
                           f"VALUES ({dept_id}, '{dept_name}', '{dept_head}', '{location}');\n")

        # Generate Courses data
        for course_id in range(1, num_records + 1):
            course_name = f"Course-{course_id}"
            course_desc = f"Description of Course-{course_id}"
            credits = random.randint(1, 4)
            dept_id = random.randint(1, 5)
            sql_file.write(f"INSERT INTO Courses (CourseID, CourseName, CourseDescription, Credits, DepartmentID) "
                           f"VALUES ({course_id}, '{course_name}', '{course_desc}', {credits}, {dept_id});\n")

        # Generate Instructors data
        for instructor_id in range(1, num_records + 1):
            name = f"Instructor-{instructor_id}"
            email = f"instructor{instructor_id}@example.com"
            phone = f"123-456-{instructor_id:02d}00"
            dept_id = random.randint(1, 5)
            sql_file.write(f"INSERT INTO Instructors (InstructorID, Name, Email, Phone, DepartmentID) "
                           f"VALUES ({instructor_id}, '{name}', '{email}', '{phone}', {dept_id});\n")

        # Generate Students data
        for student_id in range(1, num_records + 1):
            name = f"Student-{student_id}"
            email = f"student{student_id}@example.com"
            phone = f"987-654-{student_id:02d}00"
            dob = random_date()
            program_major = f"Program-{student_id}"
            sql_file.write(f"INSERT INTO Students (StudentID, Name, Email, Phone, DateOfBirth, ProgramMajor) "
                           f"VALUES ({student_id}, '{name}', '{email}', '{phone}', '{dob}', '{program_major}');\n")

        # Generate Classrooms data
        for classroom_id in range(1, num_records + 1):
            location = f"Location-{classroom_id}"
            capacity = random.randint(20, 100)
            classroom_type = random.choice(["Lecture Hall", "Lab", "Seminar Room"])
            sql_file.write(f"INSERT INTO Classrooms (ClassroomID, Location, Capacity, Type) "
                           f"VALUES ({classroom_id}, '{location}', {capacity}, '{classroom_type}');\n")

        # Generate ClassSchedule data
        for class_id in range(1, num_records + 1):
            course_id = random.randint(1, num_records)
            instructor_id = random.randint(1, num_records)
            classroom_id = random.randint(1, num_records)
            start_time = random_time()
            end_time = random_time()
            date = random_date()
            sql_file.write(f"INSERT INTO ClassSchedule (ClassID, CourseID, InstructorID, ClassroomID, StartTime, EndTime, Date) "
                           f"VALUES ({class_id}, {course_id}, {instructor_id}, {classroom_id}, '{start_time}', '{end_time}', '{date}');\n")

        # Generate Enrollment data
        for enrollment_id in range(1, num_records + 1):
            student_id = random.randint(1, num_records)
            class_id = random.randint(1, num_records)
            enrollment_date = random_date()
            sql_file.write(f"INSERT INTO Enrollment (EnrollmentID, StudentID, ClassID, EnrollmentDate) "
                           f"VALUES ({enrollment_id}, {student_id}, {class_id}, '{enrollment_date}');\n")

        # Generate Semesters data
        for semester_id in range(1, 4):
            semester_name = f"Semester-{semester_id}"
            start_date = random_date()
            end_date = random_date()
            academic_year = random.randint(2010, 2023)
            sql_file.write(f"INSERT INTO Semesters (SemesterID, SemesterName, StartDate, EndDate, AcademicYear) "
                           f"VALUES ({semester_id}, '{semester_name}', '{start_date}', '{end_date}', {academic_year});\n")

        # Generate Prerequisites data
        for course_id in range(1, num_records + 1):
            prerequisite_course_id = random.randint(1, num_records)
            prerequisite_type = random.choice(["Mandatory", "Recommended"])
            sql_file.write(f"INSERT INTO Prerequisites (CourseID, PrerequisiteCourseID, PrerequisiteType) "
                           f"VALUES ({course_id}, {prerequisite_course_id}, '{prerequisite_type}');\n")

def main():
    # Set the number of records to generate
    num_records = 10

    # Call the function to generate data and export it to SQL file
    generate_data(num_records)

if __name__ == "__main__":
    main()